name: Queue
favicon: null
layout_spectrum: 0
typography_spectrum: 0.22326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d733'
    - '#45004f'
    - '#5edcd2'
    - '#fdfdfd'
    - '#ff1400'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
