name: Queue
favicon: null
layout_spectrum: 0.519775525899604
typography_spectrum: 0.016328277066349983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4864647127687931
  lightness: 0.9089805514086038
  saturation: 0.6725240780506283
  rhythmicContrast: 0.13591134455054998
purpose: []
